# Generated by Django 2.2.24 on 2025-07-03 10:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер в формате +7XXXXXXXXXX', max_length=128, region='RU', verbose_name='Номер владельца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='living_area',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество жилых кв.метров'),
        ),
    ]
