# Generated by Django 2.2.24 on 2025-07-06 16:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_link_owners_to_flats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер владельца'),
        ),
    ]
